# Generated by Django 3.1.5 on 2022-08-01 08:11

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(unique=True)),
                ('p_name', models.CharField(max_length=225)),
                ('p_brand', models.CharField(max_length=225)),
                ('production_date', models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date.today)])),
                ('price', models.FloatField()),
                ('expiration_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
